image: Visual Studio 2017

version: 0.0.0-{build}
build_script:  
  - ps: .\build.ps1 -Target "Default"

artifacts:
  - path: artifacts\*.nupkg
    name: Packages

test: off
skip_branch_with_pr: true

on_failure:
  - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-$(Get-Date -format HHmmss)-failed"
  
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/graphql-dotnet/api/v2/package
    api_key:
      secure: +l1vfBMajn1WfmXkQ2LdILKxK4fQ5AHSnnU1kf11Bn1xRGUOTCdPhLwHx232piEn
    skip_symbols: true
    on:
      branch:
        - develop
        - master

for:

-
  branches:
    only:
      - master

  skip_non_tags: true
