image: Visual Studio 2017

version: 0.0.0-{build}
build_script:  
  - ps: .\build.ps1 -Target "Default"

artifacts:
  - path: artifacts\*.nupkg
    name: Packages

test: off
skip_tags: false
skip_branch_with_pr: true

cache:
# - '%USERPROFILE%\.nuget\packages' <- slow builds
- tools -> tools\packages.config

on_failure:
  - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)-$(Get-Date -format HHmmss)-failed"
